### ISSUE TITLE
complete music player functionality

### ISSUE THREAD

**Issue by eemshi** [mmmanyfold/princess-nokia#32]
- [ ]  look into timing issue for mobile

**Comment by dviramontes** [comment]
@eemshi do you think there is something in cloudfront that could help us stream better for mobile ?

**Comment by eemshi** [comment]
I think CloudFront is doing its thing. Cuz it works for me now

**Comment by dviramontes** [comment]
Same here actually, good to close this then ?

**Comment by eemshi** [comment]
Actually it's kind of off and on. Not working now. I wonder if we should have a back up plan also in case something goes wrong on Tuesday.

**Comment by eemshi** [comment]
But yes I think we can close this one

**Comment by dviramontes** [comment]
k, opening a diff issue for the other stuff.
