### ISSUE TITLE
fix routing for main site

### ISSUE THREAD

**Issue by eemshi** [mmmanyfold/princess-nokia#64]
![screen shot 2016-09-05 at 1 17 08 pm](https://cloud.githubusercontent.com/assets/10643091/18255859/44ddd69a-736b-11e6-81bf-c2d09b34c981.png)

**Comment by eemshi** [comment]
![screen shot 2016-09-05 at 1 17 08 pm](https://cloud.githubusercontent.com/assets/10643091/18255853/2d6143ee-736b-11e6-9042-8946f920921c.png)

**Comment by dviramontes** [comment]
Fixed in bucket config. Closing.
